#! /bin/bash

if [[ $1 == "test" ]]
then
  PSQL="psql --username=postgres --dbname=worldcuptest -t --no-align -c"
else
  PSQL="psql --username=freecodecamp --dbname=worldcup -t --no-align -c"
fi

# Do not change code above this line. Use the PSQL variable above to query your database.
echo $($PSQL "TRUNCATE TABLE teams ,games")
cat games.csv | while IFS="," read YEAR ROUND WINNER OPPONENT WINNER_GOALS OPPONENT_GOALS
do
TEAMS=$($PSQL "SELECT name FROM teams WHERE name='$WINNER'")
  if [[ $WINNER != "name" ]]
  then 
    if [[ -z $TEAMS ]]
    then
      INSERT_TEAM=$($PSQL "INSERT INTO teams(name) VALUES('$WINNER')") 
      if [[ $INSERT_TEAM == "INSERT 0 1" ]]
      then
        echo Inserted into name, $WINNER
      fi
    fi
  fi 
  TEAMS2=$($PSQL "SELECT name FROM teams WHERE name='$OPPONENT'")
  if [[ $OPPONENT != "name" ]]
  then 
    if [[ -z $TEAMS2 ]]
    then
      INSERT_TEAM2=$($PSQL "INSERT INTO teams(name) VALUES('$OPPONENT')") 
      if [[ $INSERT_TEAM2 == "INSERT 0 1" ]]
      then
        echo Inserted into name, $OPPONENT
      fi
    fi
  fi
  echo $($PSQL "DELETE  FROM teams WHERE name='winner' OR name= 'opponent'")   
    if [[ $WINNER != "name" ]]
  then
    WINNER_ID=$($PSQL "SELECT team_id FROM teams WHERE name='$WINNER'") 
    if [[ -z $WINNER_ID ]]
    then
      $WINNER_ID=null
    fi
       if [[ $OPPONENT != "name" ]]
  then   
    OPPONENT_ID=$($PSQL "SELECT team_id FROM teams WHERE name='$OPPONENT'")  
    if [[ -z $OPPONENT_ID ]]
    then
      $OPPONENT_ID=null
    fi
    INSERT_GAMES_RESULT=$($PSQL "INSERT INTO games(year,round,winner_id,opponent_id,winner_goals,opponent_goals) VALUES($YEAR, '$ROUND', $WINNER_ID, $OPPONENT_ID ,$WINNER_GOALS ,$OPPONENT_GOALS)")
  fi
  fi
done
